name: Build

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Building'
jobs:
  build-android:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository od
        uses: actions/checkout@v2
      - name: Set variables
        run: |
         HASH=$(cat SNAPSHOT_HASH)
         echo "SNAPSHOT_HASH=$HASH" >> $GITHUB_ENV
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get remove git git-man
          sudo add-apt-repository --remove --yes ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install --yes git git-svn
          sudo apt-get install -y git wget curl software-properties-common unzip python-pip python lsb-release sudo apt-transport-https
          DEBIAN_FRONTEND="noninteractive" sudo apt-get -y install tzdata
          pip install wheel
          pip install .
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          git clone https://github.com/flutter/engine.git
      - name: gclient sync
        run: |
          ROOT_DIR=`pwd`
          export PATH=$PATH:$ROOT_DIR/depot_tools
          cd engine
          git config --global user.email "reflutter@example.com" && git config --global user.name "reflutter"
          git fetch origin $(reflutter ${{env.SNAPSHOT_HASH}} -l)
          git reset --hard FETCH_HEAD
          reflutter ${{env.SNAPSHOT_HASH}} -l
          echo 'reflutter' > REFLUTTER
          git add . && git commit -am "reflutter"
          git format-patch -1 HEAD --stdout > reflutter_engine.patch
          cp reflutter_engine.patch $ROOT_DIR
          cd $ROOT_DIR
          mkdir --parents customEngine
          cd customEngine
          echo 'solutions = [{"managed": False,"name": "src/flutter","url": "'$ROOT_DIR/engine'","custom_deps": {},"deps_file": "DEPS","safesync_url": "",},]' > .gclient
          gclient sync
          reflutter ${{env.SNAPSHOT_HASH}} -l
          cd src/third_party/dart
          echo 'reflutter' > REFLUTTER
          git add . && git commit -am "reflutter"
          git format-patch -1 HEAD --stdout > reflutter_dart.patch
          cp reflutter_dart.patch $ROOT_DIR
          cd $ROOT_DIR/customEngine
          cd src/third_party/boringssl/src
          echo 'reflutter' > REFLUTTER
          git add . && git commit -am "reflutter"
          git format-patch -1 HEAD --stdout > reflutter_boringssl.patch
          cp reflutter_boringssl.patch $ROOT_DIR
          cd $ROOT_DIR/customEngine
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          target_commitish: ${{env.SNAPSHOT_HASH}}
          tag_name: android-${{env.SNAPSHOT_HASH}}
          files: |
            ./*.patch
